name: 'Terraform Drift Detection'
 
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:      # Allow manual triggers
 
permissions:
  id-token: write
  contents: read
  issues: write
 
defaults:
  run:
    working-directory: ./infra/tf-app
 
jobs:
  detect-drift:
    name: 'Detect Infrastructure Drift'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Detect Drift
        id: drift
        run: |
          terraform plan -detailed-exitcode
        continue-on-error: true
      - name: Create Issue on Drift Detection
        if: steps.drift.outcome == 'failure' && steps.drift.exitcode == 2
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Infrastructure Drift Detected',
              body: `
              # Infrastructure Drift Detected
              Terraform has detected differences between the current state and desired state of your infrastructure.
              ## What to do
              1. Review the changes in Azure Portal
              2. If changes are expected, update the Terraform configuration
              3. If changes are unexpected, investigate who/what made them
              4. Apply the correct configuration using the deployment workflow
              ## Details
              - Detected at: ${new Date().toISOString()}
              - Workflow run: [View Run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
              `
            });