name: Terraform Lint
 
on:

  pull_request:

    paths:

      - 'infra/**/*.tf'

      - '.github/workflows/terraform-lint.yml'
 
jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check

        run: |

          cd infra/tf-app

          terraform fmt -check

      - name: Terraform Init

        run: |

          cd infra/tf-app

          terraform init -backend=false

      - name: Terraform Validate

        run: |

          cd infra/tf-app

          terraform validate
 